spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cov_db
    username: root
    password: 
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
   